force-app/main/default/objects/API_Detail__mdt/API_Detail__mdt.object-meta.xml
<CustomObject>
    <description>Re-usable metadata to keep information regarding API&apos;s and associated field mappings</description>
    <label>API Detail</label>
    <pluralLabel>API Details</pluralLabel>
</CustomObject>

force-app/main/default/objects/API_Field_Mapping__mdt/API_Field_Mapping__mdt.object-meta.xml
<CustomObject>
    <description>To keep the field mapping between the source salesforce fields and the target system fields</description>
    <label>API Field Mapping</label>
    <pluralLabel>API Field Mappings</pluralLabel>
</CustomObject>

force-app/main/default/objects/API_Field_Mapping__mdt/fields/API_Detail__c.field-meta.xml
<CustomField>
    <fullName>API_Detail__c</fullName>
    <label>API Detail</label>
    <referenceTo>API_Detail__mdt</referenceTo>
    <relationshipLabel>API Field Mappings</relationshipLabel>
    <relationshipName>API_Field_Mappings</relationshipName>
    <type>MetadataRelationship</type>
</CustomField>

force-app/main/default/objects/API_Field_Mapping__mdt/fields/Target_Field_Name__c.field-meta.xml
<CustomField>
    <fullName>Target_Field_Name__c</fullName>
    <label>Target Field Name</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/APIDetailMDTSelector.cls
/*
 * Created by: Mathew
 * Description : Selector class which host the SOQL methods for the custom metadata API_Detail__mdt.
 *              
 */

public with sharing class APIDetailMDTSelector {

    public  API_Detail__mdt getWorkforcePlanningAPIDetailWithFieldMap() {
        return [SELECT DeveloperName,
                SF_Object_Name__c,
                (SELECT Id,SF_Field_Name__c,Target_Field_Name__c
                FROM API_Field_Mappings__r)
                FROM API_Detail__mdt 
                WHERE DeveloperName = 'Workforce_Planning'
                LIMIT 1];         
    }   
}