force-app/main/default/objects/API_Detail__mdt/API_Detail__mdt.object-meta.xml
<CustomObject>
    <description>Re-usable metadata to keep information regarding API&apos;s and associated field mappings</description>
    <label>API Detail</label>
    <pluralLabel>API Details</pluralLabel>
</CustomObject>

force-app/main/default/objects/API_Field_Mapping__mdt/API_Field_Mapping__mdt.object-meta.xml
<CustomObject>
    <description>To keep the field mapping between the source salesforce fields and the target system fields</description>
    <label>API Field Mapping</label>
    <pluralLabel>API Field Mappings</pluralLabel>
</CustomObject>

force-app/main/default/objects/API_Field_Mapping__mdt/fields/API_Detail__c.field-meta.xml
<CustomField>
    <fullName>API_Detail__c</fullName>
    <label>API Detail</label>
    <referenceTo>API_Detail__mdt</referenceTo>
    <relationshipLabel>API Field Mappings</relationshipLabel>
    <relationshipName>API_Field_Mappings</relationshipName>
    <type>MetadataRelationship</type>
</CustomField>

force-app/main/default/objects/API_Field_Mapping__mdt/fields/Target_Field_Name__c.field-meta.xml
<CustomField>
    <fullName>Target_Field_Name__c</fullName>
    <label>Target Field Name</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/APIFieldMappingMDTSelector.cls
public with sharing class APIFieldMappingMDTSelector {

    public Map<String, String> getWorforcePlanningApiDetails() {
        Map<String, String>fieldMapping = new Map<String, String>();
        for(API_Field_Mapping__mdt fm : [SELECT Id,SF_Field_Name__c,Target_Field_Name__c
                FROM API_Field_Mapping__mdt 
                WHERE API_Detail__r.DeveloperName = 'Workforce_Planning']){
                    fieldMapping.put(fm.SF_Field_Name__c, fm.Target_Field_Name__c);            
            }                                
        return fieldMapping;
    }  

}