force-app/main/default/objects/API_Callout__c/API_Callout__c.object-meta.xml
<CustomObject>
    <description>Used to track the API callouts and constitute a failover strategy</description>
    <label>API Callout</label>
    <nameField>
        <displayFormat>C-{000000000}</displayFormat>
        <label>API Callout Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>API Callouts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/API_Callout__c/fields/API_Name__c.field-meta.xml
<CustomField>
    <fullName>API_Name__c</fullName>
    <label>API Name</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/API_Callout__c/fields/Attempt_Type__c.field-meta.xml
<CustomField>
    <fullName>Attempt_Type__c</fullName>
    <label>Attempt Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>Retry</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/API_Callout__c/fields/Case__c.field-meta.xml
<CustomField>
    <fullName>Case__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>API Callouts</relationshipLabel>
    <relationshipName>API_Callouts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/API_Callout__c/fields/Job_Id__c.field-meta.xml
<CustomField>
    <fullName>Job_Id__c</fullName>
    <label>Job Id</label>
    <length>18</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/API_Callout__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>QUEUED</fullName>
            </value>
            <value>
                <fullName>RETRY QUEUED</fullName>
            </value>
            <value>
                <fullName>OK</fullName>
            </value>
            <value>
                <fullName>KO</fullName>
            </value>
            <value>
                <fullName>FAILED</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/Secret_Key__c.field-meta.xml
<CustomField>
    <fullName>Secret_Key__c</fullName>
    <description>Used to keep the secret key returned by the workforce planning API</description>
    <label>Secret Key</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/CaseClosureInvocableTest.cls
/*
 * Created by: Mathew
 * Description : Test class for CaseClosureInvocable            
 */

@IsTest
public with sharing class CaseClosureInvocableTest {


    @testSetup static void setupData() {
        // Ideally test data creation as part of the @testSetup can be handled using the TestDataFactory pattern.
        // Skipping the TestDataFactory pattern as complex orgs tends to have an TestDataFacory class in place and 
        // deploying this code package might overwrite the existing code.
        Case c = new Case (Status = 'New', Subject = 'Test Case', Origin='Phone');
        insert c;
    }

    @IsTest
    static void notifyWorkforcePlanningNewFailAttempt(){
        Test.setMock(HttpCalloutMock.class, new SubmitMockCallout(CONSTANTS.FAIL_MOCK_RESPONSE));
        Case kas = [Select id, ownerId from case where Subject = 'Test Case' limit 1];
        Test.startTest();
            kas.status = 'Closed';
            update kas;
        Test.stopTest();
        API_Callout__c a = [SELECT Job_Id__c, Status__c, Attempt_Type__c, Case__r.Secret_Key__c 
                            FROM API_Callout__c 
                            WHERE API_Name__c =: CONSTANTS.WP_API_NAME limit 1];
        System.assert(a!=NULL);
        System.assertEquals(a.Status__c,'KO');
        System.assertEquals(a.Attempt_Type__c,'New');
        System.assertEquals(a.Case__r.Secret_Key__c,null);

    }    

    @IsTest
    static void notifyWorkforcePlanningNewSuccessAttempt(){
        Test.setMock(HttpCalloutMock.class, new SubmitMockCallout(CONSTANTS.SUCCESS_MOCK_RESPONSE));
        Case kas = [Select id, ownerId from case where Subject = 'Test Case' limit 1];
        Test.startTest();
            kas.status = 'Closed';
            update kas;
        Test.stopTest();
        API_Callout__c a = [SELECT Job_Id__c, Status__c, Attempt_Type__c, Case__r.Secret_Key__c 
                            FROM API_Callout__c 
                            WHERE API_Name__c =: CONSTANTS.WP_API_NAME limit 1];
        System.assert(a!=NULL);
        System.assertEquals(a.Status__c,'OK');
        System.assertEquals(a.Attempt_Type__c,'New');
        System.assertEquals(a.Case__r.Secret_Key__c,'secret');
    }    

    @IsTest
    static void notifyWorkforcePlanningRetryAttempt(){
        Test.setMock(HttpCalloutMock.class, new SubmitMockCallout(CONSTANTS.FAIL_MOCK_RESPONSE));
        Case kas = [Select id, ownerId from case where Subject = 'Test Case' limit 1];
        Test.startTest();
            kas.status = 'Closed';
            update kas;
        Test.stopTest();
        List<API_Callout__c> calloutList = new List<API_Callout__c>([SELECT Job_Id__c, Status__c, Attempt_Type__c, Case__r.Secret_Key__c 
                                                                    FROM API_Callout__c 
                                                                    WHERE API_Name__c = : CONSTANTS.WP_API_NAME 
                                                                    AND Case__c =: kas.Id]);
        System.assert(calloutList!=NULL);
        System.assertEquals(calloutList.size(),2);

    }    

}