force-app/main/default/objects/API_Callout__c/API_Callout__c.object-meta.xml
<CustomObject>
    <description>Used to track the API callouts and constitute a failover strategy</description>
    <label>API Callout</label>
    <nameField>
        <displayFormat>C-{000000000}</displayFormat>
        <label>API Callout Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>API Callouts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/API_Callout__c/fields/API_Name__c.field-meta.xml
<CustomField>
    <fullName>API_Name__c</fullName>
    <label>API Name</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/API_Callout__c/fields/Attempt_Type__c.field-meta.xml
<CustomField>
    <fullName>Attempt_Type__c</fullName>
    <label>Attempt Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>Retry</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/API_Callout__c/fields/Case__c.field-meta.xml
<CustomField>
    <fullName>Case__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>API Callouts</relationshipLabel>
    <relationshipName>API_Callouts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/API_Callout__c/fields/Job_Id__c.field-meta.xml
<CustomField>
    <fullName>Job_Id__c</fullName>
    <label>Job Id</label>
    <length>18</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/API_Callout__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>QUEUED</fullName>
            </value>
            <value>
                <fullName>RETRY QUEUED</fullName>
            </value>
            <value>
                <fullName>OK</fullName>
            </value>
            <value>
                <fullName>KO</fullName>
            </value>
            <value>
                <fullName>FAILED</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/API_Detail__mdt/API_Detail__mdt.object-meta.xml
<CustomObject>
    <description>Re-usable metadata to keep information regarding API&apos;s and associated field mappings</description>
    <label>API Detail</label>
    <pluralLabel>API Details</pluralLabel>
</CustomObject>

force-app/main/default/objects/API_Field_Mapping__mdt/API_Field_Mapping__mdt.object-meta.xml
<CustomObject>
    <description>To keep the field mapping between the source salesforce fields and the target system fields</description>
    <label>API Field Mapping</label>
    <pluralLabel>API Field Mappings</pluralLabel>
</CustomObject>

force-app/main/default/objects/API_Field_Mapping__mdt/fields/API_Detail__c.field-meta.xml
<CustomField>
    <fullName>API_Detail__c</fullName>
    <label>API Detail</label>
    <referenceTo>API_Detail__mdt</referenceTo>
    <relationshipLabel>API Field Mappings</relationshipLabel>
    <relationshipName>API_Field_Mappings</relationshipName>
    <type>MetadataRelationship</type>
</CustomField>

force-app/main/default/objects/API_Field_Mapping__mdt/fields/Target_Field_Name__c.field-meta.xml
<CustomField>
    <fullName>Target_Field_Name__c</fullName>
    <label>Target Field Name</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/CaseClosureInvocable.cls
/*
 * Created by: Mathew
 * Description : Apex class with the invocable method which enqueues a job which makes 
 * an API callout to the workforce planning API on case closure and also intialises the
 * an API_Callout__c record to track the HttpRequest & HttpResponse.
 * This invocable method is re-used for retries on the API callout failure.             
 */

public with sharing class CaseClosureInvocable {

    @InvocableMethod(label='Update Workforce Planning' 
                    description='Queue a job which makes an API call to the workforce planning API to notify the case closure.'
                    category= 'Case')
    public static void  notifyWorkforcePlanning(List<FlowInput> inputs) {

        List<API_Callout__c> apiCalloutsScheduled = new List<API_Callout__c>();
        Map<String, String> fieldMap = new Map<String, String>();
        //get API details and field mapping from custom metadata
        API_Detail__mdt workforcePlanningAPIDetail= new APIDetailMDTSelector().getWorkforcePlanningAPIDetailWithFieldMap();
        if(workforcePlanningAPIDetail != null){
            if(!workforcePlanningAPIDetail.API_Field_Mappings__r.IsEmpty()){
                for(API_Field_Mapping__mdt fm : workforcePlanningAPIDetail.API_Field_Mappings__r){
                    fieldMap.put(fm.SF_Field_Name__c, fm.Target_Field_Name__c); 
                }                
            }
        }
        //field Map for workforce planning API found
        if(!fieldMap.isEmpty()){
            for(FlowInput i : inputs){
                ID jobID = System.enqueueJob(new CaseClosureQueueable(i.kase, fieldMap));
                apiCalloutsScheduled.add(new API_Callout__c(Job_ID__c = jobID, 
                                                     Case__c = i.Kase.Id,
                                                     Status__c = 'QUEUED',
                                                     API_Name__c = workforcePlanningAPIDetail.DeveloperName,
                                                     Attempt_Type__c = i.attemptType));
            }            
        }         
        if(apiCalloutsScheduled.size()>0){
            insert apiCalloutsScheduled;
        }        

    } 
    /*
        Apex type used as type of the input param to the invocable method
    */
   public class FlowInput{
        @InvocableVariable
        public Case kase;
        @InvocableVariable
        public String attemptType;
    }       

}